#!/bin/sh
set -e # abort on any error

# This tool copies a whole commit.
#
# This tool copies a whole commit, but instead of just cherry-picking it, also
# the correct author and date will be set in the environment via git info.


#
# config
#
mode="just-copy"


#
# get cmd options
#
while getopts ":en" opt
do
	# do some pre checks
	case $opt in
		e) export mode="edit" ;;      # edit commit message
		n) export mode="no-commit" ;; # do not commit


		\?)
			echo "Invalid option: -$OPTARG" >&2
			exit 1
		;;

		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
		;;
	esac
done

# shift for optional arguments
shift $((OPTIND-1))

# get commit ID (first argument after cmd options)
if [ -z $1 ]
then
	echo "No comit set" >&2
	exit 1
fi

for commit in $@
do
	# set environment
	eval $(git info -e $commit)

	# cherry pick commit
	case $mode in
		just-copy) git cherry-pick $commit ;;
		edit) git cherry-pick --edit $commit ;;
		no-commit) git cherry-pick --no-commit $commit ;;
	esac
done

if [ "$mode" = "no-commit" ]
then
	echo ""
	echo "you can commit with the following command:"
	echo ""
	git info -s $commit
fi
